spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Hongkong
  resources:
    static-locations: classpath:/static/,classpath:/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/

server:
  port: 8099
  servlet:
    context-path: /wxs
logging:
  config: classpath:logback-spring.xml
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
